CREATE TABLE IF NOT EXISTS players (
    player_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    current_number NUMERIC (5) NOT NULL,
    height NUMERIC (3,2) NOT NULL,
    birth_city TEXT NOT NULL,
    birth_state TEXT NOT NULL,
    birth_country TEXT NOT NULL,
    image_url TEXT
);

CREATE TABLE IF NOT EXISTS clubs (
    club_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    icon_url TEXT,
    league_id INTEGER NOT NULL,
    stadium_name TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    inception INTEGER
);

CREATE TABLE IF NOT EXISTS coaches (
    coach_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    birth_city TEXT NOT NULL,
    birth_state TEXT NOT NULL,
    birth_country TEXT NOT NULL,
    image_url TEXT,
    current_club_id INTEGER NOT NULL,
    years_at_current_club INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS game_day_player_stats (
    game_day_player_stats_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_id INTEGER NOT NULL,
    game_date TEXT NOT NULL,
    club_id INTEGER NOT NULL,
    position TEXT NULL NULL,
    started_game BOOLEAN NOT NULL,
    minutes_played INTEGER NOT NULL,
    assists INTEGER NOT NULL,
    shots INTEGER NOT NULL,
    shots_on_goal INTEGER NOT NULL,
    fouls_committed INTEGER NOT NULL,
    offsides INTEGER NOT NULL,
    yellows INTEGER NOT NULL,
    reds INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS players_clubs (
    player_club_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_id INTEGER NOT NULL,
    club_id INTEGER NOT NULL,
    current_club BOOLEAN
);

CREATE TABLE IF NOT EXISTS players_coaches (
    player_coach_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_id INTEGER NOT NULL,
    coach_id INTEGER NOT NULL,
    current_coach BOOLEAN
);

CREATE TABLE IF NOT EXISTS football_leagues (
    football_league_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    league_name TEXT NOT NULL,
    inception INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS football_divisions (
    football_divisions_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    division_name TEXT NOT NULL,
    football_league_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS national_team_fixtures (
    national_team_fixture_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fixture_name TEXT NOT NULL,
    fixture_date TEXT NOT NULL,
    capped BOOLEAN NOT NULL,
    friendly BOOLEAN NOT NULL,
    country TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS coaches_clubs (
    coach_club_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    coach_id INTEGER NOT NULL,
    club_id INTEGER NOT NULL,
    current_club BOOLEAN
);